### PR TITLE
Benchmarks updated; some tests parametrized

### PR DESCRIPTION
**Pull request by ml31415**
- Restkit removed from benchmarks as it seems discontinued
- httpx added to benchmarks
- Some test cases fixed or improved using pytest parametrization
- publish.yaml github actions updated

### CODE REVIEW

**Comment by cyberw** [comment]
Should I publish a release?

**Comment by ml31415** [comment]
I'm still working on it. Probably good to wait one or two more days.

**Comment by cyberw** [comment]
Ok! I dont mind doing a 2.1.1 soon after, keeping the 2.0->2.1 mainly consisting of the dropped <3.9 support.

**Comment by ml31415** [comment]
Ok, then feel free to do the release. Just pushed my last changes for today. I hope the action updates in the publish workflow didn't mess up anything.

**Comment by cyberw** [comment]
Hmm... there seems to be some flakiness with httpbin tests. https://github.com/geventhttpclient/geventhttpclient/actions/runs/8621840724

I have already made the git tag and GH release, but held off on triggering the "publish" action.

**Comment by ml31415** [comment]
See  #198 . It's harmless, but we need some more reliable solution for testing I guess. Even if this might be some temporary overload of httpbin. It's not the first time.

**Comment by cyberw** [comment]
I triggered the publish. Not sure whether httpbin is flaky or throttling us somehow.

**Comment by cyberw** [comment]
Publish failed, maybe related to the switch to pyproject.toml? https://github.com/geventhttpclient/geventhttpclient/actions/runs/8622216864/job/23632872268

**Comment by ml31415** [comment]
`Checking dist/UNKNOWN-0.0.0.tar.gz: ERROR    InvalidDistribution: Metadata is missing required fields: Name.  `

Name is present in `pyproject.toml`. It should not be necessary anymore in `setup.py`, so I had removed all metadata from there. Initially I had tried to leave the metadata in both files, but then setuptools came up with warning of overriding the settings.

In general, setuptools are currently some major pain with `pyproject.toml` compatibility. They seem not really in the mood, to proactively support entries in their `pyproject` tools section and rather wait for some PEP discussions to end for some python wide standard. That's the only reason why I couldn't remove `setup.py` and `MANIFEST.in`. And there are several more such bug reports pending for ages already. The more I have to mess with setuptools, the more I feel tempted to try out some other build tool, poetry or hatchling maybe.

**Comment by cyberw** [comment]
I think it should be fixable with setuptools too (havent investigated though)

I'm a little skeptical to poetry because of its poor speed and complexity. Also it seems very focused on applications as opposed to libraries. Never tried hatchling, but it does seem to be gaining some traction recently, maybe that is a good thing to try...

**Pull request merged**
