### PR TITLE
Fix publishing build issue

### PR DESCRIPTION
**Pull request by ml31415**

### CODE REVIEW

**Comment by ml31415** [comment]
@cyberw Plese delete this published file from pypi. I didn't cancel the build in time. The publish should be fixed now. Anyways, would be a good idea to setup testpypi for such things.

**Comment by cyberw** [comment]
Builds can't really be re-uploaded, but I can yank it. Want me to do that? 

Then I can make a 2.1.1 (it isnt possible to overwrite stuff on pypi, even if it has been deleted)

**Comment by cyberw** [comment]
I yanked 2.1.0, and prepared a release, but now the build is consistently getting timeouts for 3.11. Weird. https://github.com/geventhttpclient/geventhttpclient/actions/runs/8642598269/job/23694056639

**Comment by cyberw** [comment]
Never mind, it worked on the fourth attempt `¯\_(ツ)_/¯ `

**Comment by ml31415** [comment]
Yeah, httpbin.org really killed the testing. Gone for good now.

**Comment by cyberw** [comment]
Hmm... publishing got stuck on another issue: https://github.com/geventhttpclient/geventhttpclient/actions/runs/8642671493/job/23694406553

**Comment by ml31415** [comment]
Could this be an issue of the previous half-successful run?

**Pull request merged**
