### PR TITLE
Enable ppc64le wheels

### PR DESCRIPTION
**Pull request by mgiessing**
Minimal patch to enable ppc64le wheels (similar to enablement of aarch64).
This is no change-contentwise and just aims to support Power CPU Architecutre :-)

### CODE REVIEW

**Comment by cyberw** [comment]
I’d prefer not to stop testing older versions (especially 3.7 which is still widely used). There should be some way to handle it.

**Comment by mgiessing** [comment]
Issue was that for tests ubuntu-latest was used (22.04), however one failure was python3.6 is not available and therefore needed to switch to ubuntu-20.04 for the test runner.
That also seem to have fixes the SSL issue. I _assume_ that in those older python version it didn't get updated and thus created the error.
On my test branch all tests are running successfully now! --> https://github.com/mgiessing/geventhttpclient/actions/runs/4407864260

**Comment by mgiessing** [comment]
Yes - that would be very helpful if you could release a new minor version to have it released via pypi :) 
Thanks!

**Comment by cyberw** [comment]
👍👍

**Pull request merged**
