### PR TITLE
Vendor llhttp as submodule

### PR DESCRIPTION
**Pull request by miedzinski**
On @cyberw suggestion in https://github.com/geventhttpclient/geventhttpclient/pull/156#issuecomment-1250891988 I've changed vendoring of llhttp to git submodule. The ideal way would be leveraging distro package managers, but llhttp doesn't seem to be packaged by any major distros, so we're left with using submodules.

Also this PR bumps llhttp to v8.1.0. Changes: https://github.com/nodejs/llhttp/compare/v6.0.6...v8.1.0.

### CODE REVIEW

**Comment by cyberw** [comment]
Looks amazing. Thanks! I'll make a new release once I have merged.

**Comment by cyberw** [comment]
This build is taking forever...

**Comment by miedzinski** [comment]
Yeah, something is definitely wrong. I'll take a look.

**Comment by miedzinski** [comment]
Looks like I've ran tests in a venv without geventhttpclient rebuilt, my fault. llhttp v7.0.0+ isn't compatible anymore, so I've bumped it to v6.0.10 only (patch version change). llhttp had some breaking changes (https://github.com/nodejs/llhttp/releases/tag/release%2Fv7.0.0), so that's probably a reason. I'll try to upgrade it in another PR later.

Tests are passing now and I've done some requests to real web servers with success.

**Comment by bollwyvl** [comment]
it would be lovely if PyPI sdist still included the source of the exact version used

**Pull request merged**
