### PR TITLE
Move project source back to src/geventhttpclient

### PR DESCRIPTION
**Pull request by ml31415**
Moving the sources back to `src` makes sure that the tests are run against the installed package.

See discussion in https://github.com/geventhttpclient/geventhttpclient/issues/189 and recommendation https://hynek.me/articles/testing-packaging/

### CODE REVIEW

**Comment by ml31415** [comment]
@kloczek Does that work with your patches or you need further changes?

**Comment by ml31415** [comment]
@cyberw What's your thought on that? I'm in general not a big fan of this `src` folders, but the point of testing against the installed package is valid.

**Comment by cyberw** [comment]
I dont really have an opinion. If it makes sense to you then go for it :)

**Comment by ml31415** [comment]
Yeah, not in the mood right now to experiment with the other options presented. LGTM.

**Comment by kloczek** [comment]
> @kloczek Does that work with your patches or you need further changes?

I'll check everything on next release.

**Pull request merged**
